### ISSUE TITLE
Support for Magento base directory not being at the root of the release directory?

### ISSUE THREAD

**Issue by aingham** [webgriffe/deployer-magento2#1]
Hi,

In our M2 repo we have the Magento files within a /htdocs/magento, This seems to cause a problem with this recipe (and presumably the original Deployer M2 recipe), as in numerous places it assumes that Magento will be in the root of the release directory.

For example, when it runs 'composer install' it does so in the release directory, but in our case the composer.json file is actually within /htdocs/magento. Another example is that it creates folders, e.g. 'pub' in the release directory, but in our case they need to be created within /htdocs/magento.

I was thinking of customising by adding a 'magento_folder' setting and then including this in the path whenever the script needs to do something based on the Magento directory.

I'd be interested to get your thoughts on this.

Thanks,

Andy

**Comment by mmenozzi** [comment]
Hi @aingham,
it's true that this recipe will not support Magento installed in a subdirectory but this is a very uncommon situation. Magento 2 already have the `pub` directory where the webserver's document root should be pointed at.

So we won't support this case here in our recipe.
Anyway feel free to fork this repository and use your fork with the `magento_folder` customization.

Bye!

**Comment by aingham** [comment]
Thanks Manuele. As you say `pub` is the document root, and we're running from that, so I've now reconfigured the project to have magento in its root and removed my customisations. Thanks again, Andy
