### ISSUE TITLE
Command magento:upgrade:db run setup:upgrade without checking if is necessary

### ISSUE THREAD

**Issue by giuseppemorelli** [webgriffe/deployer-magento2#3]
With this command `bin/magento setup:db:status --no-ansi` we can check if we need to run setup:upgrade so we can avoid to run a setup:upgrade and save offline time

**Comment by lamasfoker** [comment]
Done with this [commit](https://github.com/webgriffe/deployer-magento2/commit/c481930cc416d45de7933854582d4835f7aaff99).
